# this is a development profile

spring:
  redis:
  data:
    mongodb:
      uri: ${mongodb_uri}
      database: journaldb
      auto-index-creation: true
    redis:
      port: 6379



jwt:
  secret:
    key: ${jwt_secret_key}



  #mySQL configuration
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#
#  datasource:
#    url: jdbc:mysql://localhost:3306/journalEntry
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver


server:
  port: 8080

